_target_: the_well.benchmark.trainer.Trainer
epochs: 200
val_frequency: 1
rollout_val_frequency: 1
short_validation_length: 8
max_rollout_steps: 8
num_time_intervals: 5
make_rollout_videos: True
checkpoint_frequency: 0 # Frequency of saving checkpoints. If 0, only use best/most recent. Setting this to 1 uses A LOT of disk space.
# enable_amp: False
loss_fn: the_well.benchmark.metrics.MSE
checkpoint_path: "" # This is a default that is overridden by the code
